Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
> conda info --json
> /bin/python ~/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/interpreterInfo.py
> /usr/include/python3.7 ~/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/interpreterInfo.py
Python interpreter path: /bin/python3
Starting Pylance language server.
Error 2021-12-08 15:34:43: Failed to start language server, Class name = r, completed in 546ms, has a falsy return value, Arg 1: <Uri:/home/pi/class/gpio/flask/Gui_Led_Thread.py>, Arg 2: {"sysPrefix":"/usr","envType":"Global","envName":"","envPath":"","path":"/bin/python3","architecture":2,"sysVersion":"3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]","version":{"raw":"3.7.3","major":3,"minor":7,"patch":3,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.7.3 32-bit"}, Return Value: undefined [Error: Cannot find module '/home/pi/.vscode/extensions/ms-python.vscode-pylance-2021.12.0/dist/extension.bundle.js'
Require stack:
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
	at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
	at Function.h._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js:1:38461)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26603)
	at w._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12894)
	at w._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11867)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/code/resources/app/out/vs/loader.js',
    '/usr/share/code/resources/app/out/bootstrap-amd.js',
    '/usr/share/code/resources/app/out/bootstrap-fork.js'
  ]
}
Error 2021-12-08 15:34:43: [Error: Cannot find module '/home/pi/.vscode/extensions/ms-python.vscode-pylance-2021.12.0/dist/extension.bundle.js'
Require stack:
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
	at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
	at Function.h._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js:1:38461)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26603)
	at w._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12894)
	at w._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11867)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/code/resources/app/out/vs/loader.js',
    '/usr/share/code/resources/app/out/bootstrap-amd.js',
    '/usr/share/code/resources/app/out/bootstrap-fork.js'
  ]
}
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-12-08 15:34:43: Failed to activate language server, Class name = a, completed in 559ms, has a falsy return value, Arg 1: <Uri:/home/pi/class/gpio/flask/Gui_Led_Thread.py>, Arg 2: {"sysPrefix":"/usr","envType":"Global","envName":"","envPath":"","path":"/bin/python3","architecture":2,"sysVersion":"3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]","version":{"raw":"3.7.3","major":3,"minor":7,"patch":3,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.7.3 32-bit"}, Return Value: undefined [Error: Cannot find module '/home/pi/.vscode/extensions/ms-python.vscode-pylance-2021.12.0/dist/extension.bundle.js'
Require stack:
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
	at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
	at Function.h._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js:1:38461)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26603)
	at w._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12894)
	at w._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11867)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/code/resources/app/out/vs/loader.js',
    '/usr/share/code/resources/app/out/bootstrap-amd.js',
    '/usr/share/code/resources/app/out/bootstrap-fork.js'
  ]
}
Error 2021-12-08 15:34:43: Failed to activate a workspace, Class name = m, completed in 11907ms, has a falsy return value, Arg 1: <Uri:/home/pi/class/gpio/flask/Gui_Led_Thread.py>, Return Value: undefined [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:153777
	at m (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154074)
	at e (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154565)
	at Object.t.plan (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:155228)
	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151812
	at e._get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151721)
	at e.getTagged (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150524)
	at e.getNamed (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150616)
	at a.get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:78:330351)
	at _.createRefCountedServer (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:193687)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _.activate (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:191145)
	at async Promise.all (index 5)
	at async m.activateWorkspace (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:186692)]
Error 2021-12-08 15:34:43: Failure during activation. [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:153777
	at m (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154074)
	at e (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154565)
	at Object.t.plan (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:155228)
	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151812
	at e._get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151721)
	at e.getTagged (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150524)
	at e.getNamed (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150616)
	at a.get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:78:330351)
	at _.createRefCountedServer (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:193687)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _.activate (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:191145)
	at async Promise.all (index 5)
	at async m.activateWorkspace (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:186692)]
Error 2021-12-08 15:34:43: sendStartupTelemetry() failed. [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:153777
	at m (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154074)
	at e (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:154565)
	at Object.t.plan (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:155228)
	at /home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151812
	at e._get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:151721)
	at e.getTagged (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150524)
	at e.getNamed (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:150616)
	at a.get (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:78:330351)
	at _.createRefCountedServer (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:193687)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _.activate (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:191145)
	at async Promise.all (index 5)
	at async m.activateWorkspace (/home/pi/.vscode/extensions/ms-python.python-2021.11.1422169775/out/client/extension.js:52:186692)]
Error 2021-12-08 15:42:32: Error while running worker[Worker 2]. undefined
Error 2021-12-08 15:42:32: Error while running worker[Worker 1]. undefined
